// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Contexts;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(QuizContext))]
    partial class QuizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webapi.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("QuizAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("QuizItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizItemId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("webapi.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuizOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizOwnerId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("webapi.Models.QuizItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizItems");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("webapi.Models.Answer", b =>
                {
                    b.HasOne("webapi.Models.QuizItem", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuizItemId");
                });

            modelBuilder.Entity("webapi.Models.Quiz", b =>
                {
                    b.HasOne("webapi.Models.User", "QuizOwner")
                        .WithMany()
                        .HasForeignKey("QuizOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizOwner");
                });

            modelBuilder.Entity("webapi.Models.QuizItem", b =>
                {
                    b.HasOne("webapi.Models.Quiz", null)
                        .WithMany("QuizItems")
                        .HasForeignKey("QuizId");
                });

            modelBuilder.Entity("webapi.Models.Quiz", b =>
                {
                    b.Navigation("QuizItems");
                });

            modelBuilder.Entity("webapi.Models.QuizItem", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
